name: Deploy Docker React
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t armagandalkiran/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true armagandalkiran/docker-react npm test

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Render
        run: render login --accessToken=${{ secrets.RENDER_TOKEN }}

      - name: Deploy to Render
        run: render up --name=${{ secrets.RENDER_SERVICE_NAME }} --docker-image=armagandalkiran/docker-react
