name: Deploy Docker React
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t armagandalkiran/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true armagandalkiran/docker-react npm test

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Render
        run: |
          curl -X POST https://render.com/api/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploy \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
